# /*****************************************************************
# //
# //  NAME:		Ehsan Kourkchi
# //
# //  HOMEWORK:		9
# //
# //  CLASS:		ICS 212
# //
# //  INSTRUCTOR:	Ravi Narayan
# //
# //  DATE:		December 01, 2013           
# //
# //  FILE:		Makefile        
# //
# //  DESCRIPTION:	Makefile for "hw09.c"
# //
# //****************************************************************/


all: hw09.c
	cc -o tcp_hw09  hw09.c

.PHONY: clean

clean:
	rm -f *.o